### ISSUE TITLE
Remove Verbose slick logging from running from sbt

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#103]

**Comment by jfalkner** [comment]
Please provide an example. I'll try running analysis and see if it appears there.

**Comment by jfalkner** [comment]
Here is what I'm seeing when running analysis.

```bash
[info] Loading project definition from /Users/jfalkner/tokeep/git/PacificBiosciences/smrtflow/project
[info] Set current project to smrtflow (in build file:/Users/jfalkner/tokeep/git/PacificBiosciences/smrtflow/)
[info] Running com.pacbio.secondary.smrtserver.appcomponents.SecondaryAnalysisServer 
[info] 2016-05-31  INFO [main] c.p.s.s.a.SecondaryAnalysisServer$ - Starting App
...
[info] 2016-05-31  DEBUG[smrtlink-analysis-server-akka.actor.default-dispatcher-3] o.f.c.i.u.s.c.ClassPathScanner - Filtering out resource: db/migration/V1__InitialSchema$$anonfun$slickMigrate$1$$anonfun$4.class (filename: V1__InitialSchema$$anonfun$slickMigrate$1$$anonfun$4.class)
[info] 2016-05-31  DEBUG[smrtlink-analysis-server-akka.actor.default-dispatcher-3] o.f.c.i.u.s.c.ClassPathScanner - Filtering out resource: db/migration/V1__InitialSchema$$anonfun$slickMigrate$1.class (filename: V1__InitialSchema$$anonfun$slickMigrate$1.class)
```

These log messages are all expected because of #91. Is the ask here to silence all the verbose logging or to silence just slick related messages? It'd be unusual to treat one type of log specially outside of the typical log level use.

**Comment by skinner** [comment]
I wanted the server to log to stdout by default; I didn't ask for the log level to be DEBUG.

The previous server no-arg default was to log to stdout at INFO level.  Let's make that the default again.

The fact that the command line argument is named `--debug` makes it sound like it sets both destination and log level; maybe those settings should be separate arguments.

**Comment by jfalkner** [comment]
I'll get a PR up to switch to DEBUG as default and think up a more descriptive name for `--debug`. Good point in that it implies log level. Best name I can think of right now is `--log2console`.
