### ISSUE TITLE
Style Guide Improvements

### ISSUE THREAD

**Issue by jfalkner** [PacificBiosciences/smrtflow#117]
A catch-all for linking style guide improvements or otherwise improving [`style_guide.md`](https://github.com/PacificBiosciences/smrtflow/blob/master/style_guide.md). Provides a thread for comments and discussion too.

Here is a short list of features that probably should get added but were punted from v1 in #95.
- Check/Enforce a [100 char line limit](http://twitter.github.io/effectivescala/#Formatting-Whitespace). Easy to check but requires a lot of code reformatting.
- Check/Enforce [explicit return types in public methods](http://docs.scala-lang.org/style/types). Easy to enable but requires lots of code refactoring.
- Add a git pre-commit hook and example use in docs
- Add a PR pre-merge check in GitHub

**Comment by mpkocher** [comment]
1. resolved by use of scalafmt
2. Still needs to be improved (motivated more for improving compilation times)
3. resolved by use of scalamft
4. resolved by use of `sbt scalafmt::test` pre-commit test
