### ISSUE TITLE
Diagnose Spray performance and better understand config

### ISSUE THREAD

**Issue by jfalkner** [PacificBiosciences/smrtflow#122]
Placeholder ticket for the work to help resolve the timeout issues @mpkocher highlighted at today's meeting. sqlite may be the culprit here, but we need to explain what is going on.

@skinner and @natechols are focusing on everything up through Slick. @jfalkner to work through the Spray side.

@mpkocher where is the stress test script and how to run?

**Comment by jfalkner** [comment]
Is this the stress test? https://github.com/PacificBiosciences/smrtflow/pull/114

**Comment by jfalkner** [comment]
Here is `stress.py` from @mpkocher. I think this is the stress test he mentioned on the call.

**Comment by jfalkner** [comment]
Some notes about using the code from #115 and `stress.py`.

```
# already merged in master -- use it
git checkout master

# clean the old dir (optional)
make dataclean

# copy the data locally. must be on VPN
make test-data/smrtserver-testdata
```

And here is where it breaks. I think I need a different repo installed.

```
# duplicates the data a bunch, changing UUIDs
make test-data/copied-datasets
# tries to stress the server with uploads
make test-stress-mass-import
```

**Comment by jfalkner** [comment]
PacificBiosciences/pbsmrtpip has the `dataset` command. Following the instructions in the [`python.md` README](https://github.com/PacificBiosciences/dev_readme/blob/master/python.md) gets you setup.

```bash
(ENV) jfalkner-mac:pbsmrtpipe jfalkner$ dataset
usage: dataset [-h] [--version] [--log-file LOG_FILE]
               [--log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL} | --debug | --quiet | -v]
               [--strict] [--skipCounts]
...
```

**Comment by jfalkner** [comment]
The stress test assumes that you have the `smrt-server-analysis` code running. Use the make target below.

```
# run analysis via make
make start-smrt-server-analysis
```
And in a diff shell, tmux, etc.
```
# run the stress test via pbsmrtpipe VENV
make test-stress-mass-import
```

**Comment by jfalkner** [comment]
I'm successfully running the stress test and profiling the JVM. I'll dig in to the Spray docs and post more notes as interesting things are observed.

**Comment by jfalkner** [comment]
From just the profiler, I'm currently seeing that Spray/akka is using 14 dispatcher threads to handle messages (presumably HTTP connections) and a worker pool of 5 threads to run tasks. The framework seems to randomly use all dispatchers and works, meaning it doesn't seem that a Spray/akka config issues is the likely bottleneck. No huge perf outlier based on method timing.

Here is a snapshot showing a stack trace where our code starts. e.g. Slick and JDBC.

<img width="1308" alt="screen shot 2016-06-03 at 11 10 26 am" src="https://cloud.githubusercontent.com/assets/855834/15783411/0aacb128-297c-11e6-8084-08ff8df954ea.png">

**Comment by jfalkner** [comment]
Looks like running the above `make test-stress-mass-import` does HTTP requests in serial. I didn't look at the source to confirm, but it doesn't seem to fail at all. Running `python stress.py`seems to do the needed concurrent HTTP requests. Lots of failures observed.

Note, make sure to `sbt clean` between server runs to blow up the `db` dir.

**Comment by jfalkner** [comment]
@mpkocher @skinner @natechols 

The JVM profiling seems to say that the main perf bottleneck is sqlite, by far. It appears most of the code is using correct executor-style thread pooling and non-blocking. We're not suffering from JVM thread blocking issues. Probably just sqlite blocking issues.

<img width="1308" alt="screen shot 2016-06-03 at 11 36 52 am" src="https://cloud.githubusercontent.com/assets/855834/15784263/c466eaae-297f-11e6-8ac3-6a2dd4fcbcb9.png">

**Comment by jfalkner** [comment]
@skinner @natechols 

[Here are two Slick things that seem very helpful to check](http://slick.lightbend.com/doc/2.0.0-M3/connection.html#connection-pools): make sure we're caching PreparedStatement creation (stack trace above seems to imply we aren't) and connection pooling.

> ### Connection Pools

>Slick does not provide a connection pool implementation of its own. When you run a managed application in some container (e.g. JEE or Spring), you should generally use the connection pool provided by the container. For stand-alone applications you can use an external pool implementation like DBCP, c3p0 or BoneCP.
Note that Slick uses prepared statements wherever possible but it does not cache them on its own. You should therefore enable prepared statement caching in the connection pool’s configuration and select a sufficiently large pool size.

**Comment by jfalkner** [comment]
Looks like we're passing JDBC config via [`forURL`](http://slick.lightbend.com/doc/3.1.0/database.html#using-a-jdbc-url) [here is where it lives in JobsDao.scala at the commit causing the current perf](https://github.com/PacificBiosciences/smrtflow/blob/e2534dbbf0502417104f47b05a08cc5a61ce3802/smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/actors/JobsDao.scala#L57).

Note the docs recommend using an [`application.con` TypeSafe config file](http://slick.lightbend.com/doc/3.1.0/database.html).

**Comment by mpkocher** [comment]
Note, in 3.1.0 the code running slick 2.1.0, master is now running slick 3.1.0

http://slick.lightbend.com/doc/3.1.0/

**Comment by jfalkner** [comment]
Stopped to check if this work was still needed. [Sounds like it is](https://pacbio.slack.com/archives/pbservices/p1464978831001227).


> the last release of Secondary analysis (3.1.0) of the services that runs slick 2, which is completely different that master which is running slick 3.1.0

> there’s still issues with slick 3.1.0 that aren’t completely clear and are yielding db locks and a large number of failures when running stress test

**Comment by jfalkner** [comment]
`stress.py` is now working thanks to several improvements #210, #197 and #155. 

Spray config ended up not being being what needed improvements. Closing this unless someone thinks it merits more work.
