### ISSUE TITLE
pbbundler: New model for apply-conf and port to scala

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#13]
Removing the python dependency would allow the thinner wrapping layer at the build layer (i.e., only setting JAVA_HOME).

Using lib code from the scala layer should dramatically simplify the apply-conf
- Use the scala client layer to write calls to get-status
- apply-config should load a case class from the smrt-server-analysis with the config options.
- reuse the validation layer of config.json
- simplify the fabfile, or remove it if possible with calls to ammonite.

**Comment by mpkocher** [comment]
For apply-conf, we might want to rethink the current model that's used in python code.

**Comment by natechols** [comment]
get-smrt-server-status is now as nearly as complete a replacement for get-status as I can make it, if I can only get rid of the annoying log garbage on startup...

**Comment by natechols** [comment]
+1 to rethinking apply-conf; I'm not re-writing that as-is

**Comment by mpkocher** [comment]
The apply-config exe has been ported from python to scala.
