### ISSUE TITLE
reduce asks in StatusService

### ISSUE THREAD

**Issue by skinner** [PacificBiosciences/smrtflow#134]
Looking at the StatusService today:

https://github.com/PacificBiosciences/smrtflow/blob/1fcb66e293105344b12e0d7fdda711458f7efd3b/smrt-server-base/src/main/scala/com/pacbio/common/services/StatusService.scala#L39-L43

Michael thought there were too many asks going on.

**Comment by mpkocher** [comment]
We should try to simplify this and remove the Status actor completely if possible.

**Comment by jfalkner** [comment]
I just noticed the same. I can refactor this if someone doesn't beat me to it. I already did it once in a local branch while tracing through our code's logic.

=> @jfalkner

**Comment by jfalkner** [comment]
Looks like this was already done in https://github.com/PacificBiosciences/smrtflow/commit/37711119cafb89bc04d489bd24bfb41dfa1b9dd9#diff-a0533465178790d5202502e4f973b77f
