### ISSUE TITLE
Add SF tools to Pitchfork

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#14]
This should work.
```
$> sbt smrt-analysis/pack 
$> export PATH=$(pwd)/smrt-analysis/target/pack/bin:$PATH
$> fasta-to-reference --help
```

**Comment by mhsieh** [comment]
Sorry I missed the email, will take a look at this. need to "install" sbt into the pitchfork.

**Comment by mpkocher** [comment]
Thanks, this works as expected.

It might useful an future iteration to put the package in smrflow/smrt-analysis. 

It looks like it's putting it in the root build output dir, next to the setup-env.sh
