### ISSUE TITLE
Test H2 as database to confirm our code works mechanistically

### ISSUE THREAD

**Issue by jfalkner** [PacificBiosciences/smrtflow#152]
The idea here is to try a drop in replacement database along with a larger thread pool. It should work much better than the SQLite work-arounds and confirm that our code otherwise is working.

**Comment by jfalkner** [comment]
PR is up in #182. As noted in the PR, a small test was added showing that connecting to and using H2 works via Slick. Many of the other tests pass, but likely few of the ones that use the DB. I was stuck at sorting out how to get our migrations working.

=> @smcclellan7 to take over the H2 charge as per last team meeting

**Comment by smcclellan7** [comment]
I think I'm making progress on this, but I'm getting stuck on a weird error.  Has anyone seen this before?

> [error] java.lang.InternalError: Malformed class name
> [error] 	at java.lang.Class.getSimpleBinaryName(Class.java:1450)
> [error] 	at java.lang.Class.getSimpleName(Class.java:1309)
> [error] 	at java.lang.Class.isAnonymousClass(Class.java:1411)
> [error] 	at org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner.scanForClasses(ClassPathScanner.java:102)
> [error] 	at org.flywaydb.core.internal.util.scanner.Scanner.scanForClasses(Scanner.java:75)
> [error] 	at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationResolver.resolveMigrations(JdbcMigrationResolver.java:83)
> [error] 	at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationResolver.resolveMigrations(JdbcMigrationResolver.java:45)
> [error] 	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:132)
> [error] 	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:114)
> [error] 	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:100)
> [error] 	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:44)
> [error] 	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:104)
> [error] 	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:156)
> [error] 	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:150)
> [error] 	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
> [error] 	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:150)
> [error] 	at org.flywaydb.core.Flyway.doValidate(Flyway.java:994)
> [error] 	at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
> [error] 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:921)
> [error] 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
> [error] 	at org.flywaydb.core.Flyway.execute(Flyway.java:1361)
> [error] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
> [error] 	at com.pacbio.database.Database$$anonfun$migrate$1$$anon$2.migrate(Database.scala:114)
> [error] 	at com.pacbio.database.Database$$anonfun$migrate$1.apply(Database.scala:126)
> [error] 	at com.pacbio.database.Database$$anonfun$migrate$1.apply(Database.scala:75)
> [error] 	at scala.Option.foreach(Option.scala:257)
> [error] 	at com.pacbio.database.Database.migrate(Database.scala:75)
> [error] 	at com.pacbio.database.Database$$anonfun$1.apply$mcV$sp(Database.scala:59)
> [error] 	at com.pacbio.database.Database$$anonfun$1.apply(Database.scala:59)
> [error] 	at com.pacbio.database.Database$$anonfun$1.apply(Database.scala:59)
> [error] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
> [error] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
> [error] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
> [error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> [error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> [error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> [error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> [error] Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -73
> [error] 	at java.lang.String.substring(String.java:1931)
> [error] 	at java.lang.Class.getSimpleBinaryName(Class.java:1448)
> [error] 	... 36 more

**Comment by jfalkner** [comment]
I'm not familiar with that one. Unsure what to try. 

FWIW, I've been able to use H2 sans migrations totally fine. Been using it for the initial iteration of some other code. Even sorted out a minor IntelliJ related issue so that it can be used with IntelliJ's DB tools.

**Comment by mpkocher** [comment]
Migrated to Postgres. Unnecessary now.
