### ISSUE TITLE
Why do we have an extra layer of Actors?

### ISSUE THREAD

**Issue by jfalkner** [PacificBiosciences/smrtflow#166]
CC @mpkocher @skinner @smcclellan7 

I was tracing through the Spray/Akka machinery and a few of our example requests. I don't understand why we have an extra layer of actors. What does it give us? If nothing, it is a lot of code and complexity that we can trim.

##### Tracing TCP/HTTP Connection Handling

Spray/Akka appear to rely on [java.nio.ServerSocketChannel](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/ServerSocketChannel.html) based, meaning single thread handling unlimited connections.

From `akka.io.TcpListener.scala:58`

```channelRegistry.register(channel, if (bind.pullMode) 0 else SelectionKey.OP_ACCEPT)```

The selector appears to eventually be registered vis `TcpManager.scala`, which uses `SelectionHandler.SelectorBasedManager` and allows for a configurable number of worker threads for the `ServerSocketChannel`. I didn't trace exactly how the config param map to this, but I assume we can config an arbitrary number of worker threads via `applications.conf`.

All of the above get trigger when our code invokes `Http.Bind` and registers an `ActorRef` (`BaseSmrtServerApp.scala:172`).The ActorRef we bind is `ServiceActor` (`BaseSmrtServerApp.scala:141`), which extends `RoutedHttpService` (`com.pacbio.common.packages.scala:185`) that essentially invokes `runRoute(route: Route)` from spray.routing.HttpService.
`runRoute` ends applying `type Route = RequestContext ⇒ Unit` — i.e. does the server-side logic and makes the HTTP response content.

##### HTTP Request to Route

Spray relies on Route instances that map/transform HTTP request context to our custom logic. For example, the following URL:

```
http://localhost:8070/secondary-analysis/job-manager/status
```

Maps to these lines of code in `JobManagerService.scala`.

```scala
  val statusRoutes =
    pathPrefix(SERVICE_PREFIX) {
      path("status") {
        get {
          complete {
            for {
              up <- (statusActor ? GetUptime).mapTo[Long]
            } yield SimpleStatus(manifest.id, s"${manifest.name} are up and running for ${up/1000} seconds.", up)
          }
        }
      }
```

Which really end up invoking `respondWith(uptimeMillis)` but only after queuing up the `GetUptime` case class as another Akka message and being handled by `StatusServiceActor.scala` in the below lines of code.

```scala
  def receive: Receive = {
    case GetUptime        => respondWith(uptimeMillis)
...
```

### Why can't we just do this?

Back to the original question. Below seems to be a simpler, scalable solution. What do we gain from the extra complexity?

```scala
  val statusRoutes =
    pathPrefix(SERVICE_PREFIX) {
      path("status") {
        get {
          complete {
            respondWith(uptimeMillis)
          }
        }
      }
```

Related to database work. We already are relying on queue and `ExecutionContext` when `run(DBIOAction): Future[R]` is invoked via `Database.scala` (see #155). Workers should efficiently use the DB without the extra layer of actors.

**Comment by jfalkner** [comment]
@skinner had some helpful comments on Slack

> re: actor benefits, AIUI the original idea was to only have one actor talking to the database, which was intended to prevent the DB concurrency issues we saw.  But a move to serializing database access through a one-thread AsyncExecutor may make the database actor unnecessary; removing that layer is what Steve's PR #140 is about.

>I don't know what having actors handling HTTP requests buys us; Michael/Steve might have a clearer idea there

**Comment by mpkocher** [comment]
This is the entire motivation for migrating from slick 2 to slick 3.

**Comment by jfalkner** [comment]
Thanks for noting and explaining more on Slack. I'm slow to catch up to this thread. 

C'mon #140. I bet it'll be many, many lines of deleted code
