### ISSUE TITLE
Add --non-local to 'pbservice import-dataset'

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/smrtflow#178]
Currently, importing datasets can only be done with access to the FS where the dataset exists.

Expand importing to include non-local (to where pbservice is running) importing of datasets would require:

- explicitly providing the DataSet metatype
- skipping any validation
- additional changes to the ServiceAccessLayer (TBD)

**Comment by natechols** [comment]
Wouldn't this need an explicit UUID too?

**Comment by mpkocher** [comment]
The POST request only requires metatype and path to the DataSet. The local case would have to skip the check for the import prior to the DataSet POST. 

Also, the Import job type should probably remove the required metatype and extract that from the XML file. Initially this was motivated by having an explicit interface, however, I think it's unnecessary now.
