### ISSUE TITLE
Better Commandline tool logging model

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#18]
Programmatically define and setup the logger for commandline tools. 

Currently it's using the application.conf, which is not the best model.

**Comment by jfalkner** [comment]
=> @jfalkner

@mpkocher @natechols I'll take a whack at this one. It isn't entirely clear to me what is desired. I'll bug @mpkocher more off thread. I think we just want a way to config the logger via code and no longer need the conf file. Related to that. @natechols asked about silencing some logger verbosity.

**Comment by mpkocher** [comment]
@natechols Can you post an example output of the new get status tool?

**Comment by natechols** [comment]
[DEBUG] [05/11/2016 08:42:18.026] [main] [EventStream] StandardOutLogger started
08:42:18,259 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
08:42:18,259 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
08:42:18,259 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/nechols/src/smrtflow/smrt-server-tools/target/pack/lib/smrt-server-link_2.11-0.1.1-SNAPSHOT.jar!/logback.xml]
08:42:18,260 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
08:42:18,260 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/nechols/src/smrtflow/smrt-server-tools/target/pack/lib/smrt-server-analysis_2.11-0.1.1-SNAPSHOT.jar!/logback.xml]
08:42:18,260 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/nechols/src/smrtflow/smrt-server-tools/target/pack/lib/smrt-server-link_2.11-0.1.1-SNAPSHOT.jar!/logback.xml]
08:42:18,260 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/nechols/src/smrtflow/smrt-server-tools/target/pack/lib/smrt-server-base_2.11-0.1.1-SNAPSHOT.jar!/logback.xml]
08:42:18,272 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@5ea2eb39 - URL [jar:file:/home/nechols/src/smrtflow/smrt-server-tools/target/pack/lib/smrt-server-link_2.11-0.1.1-SNAPSHOT.jar!/logback.xml] is not of type file
08:42:18,317 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
08:42:18,329 |-ERROR in ch.qos.logback.core.joran.action.PropertyAction - Could not find properties file [./logback.properties].
08:42:18,329 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:42:18,331 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
08:42:18,366 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:42:18,399 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:42:18,399 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDERR]
08:42:18,401 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:42:18,401 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
08:42:18,404 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
08:42:18,418 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@3659a50 - Will use gz compression
08:42:18,423 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:42:18,425 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: ./smrtlink-smrt-server.log
08:42:18,425 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [./smrtlink-smrt-server.log]
08:42:18,427 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
08:42:18,427 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [Slf4jLogger] to INFO
08:42:18,427 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [scala.slick] to INFO
08:42:18,427 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
08:42:18,428 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - Could not find Janino library on the class path. Skipping conditional processing.
08:42:18,428 |-ERROR in ch.qos.logback.core.joran.conditional.IfAction - See also http://logback.qos.ch/codes.html#ifJanino
08:42:18,428 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an AppenderAttachable at the top of execution stack. Near [appender-ref] line 67
08:42:18,428 |-WARN in ch.qos.logback.classic.joran.action.RootLoggerAction - The object on the top the of the stack is not the root logger
08:42:18,428 |-WARN in ch.qos.logback.classic.joran.action.RootLoggerAction - It is: ch.qos.logback.core.joran.conditional.IfAction
08:42:18,428 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:42:18,429 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@38fdfbc6 - Registering current configuration as safe fallback point

[DEBUG] [05/11/2016 08:42:18.439] [main] [EventStream(akka://get-status)] logger log1-Slf4jLogger started
[DEBUG] [05/11/2016 08:42:18.441] [main] [EventStream(akka://get-status)] Default Loggers started

**Comment by natechols** [comment]
There is a better-than-even chance I'm doing something dumb, of course.  I've also found that my calls to logger.info() produce no output, but that's even more likely a newbie error.

**Comment by jfalkner** [comment]
Thanks, please also post the command or code you are running to get this.

**Comment by natechols** [comment]
./smrt-server-tools/target/pack/bin/get-smrt-server-status --host smrtlink-bihourly --port 8081

**Comment by mpkocher** [comment]
Run `sbt smrt-server-tools/pack` for the exes to be built.

It looks like it's loading the smrtlink logback.xml config from the smrtlink project. 

Putting a custom logback.xml with a reasonable default in here https://github.com/PacificBiosciences/smrtflow/tree/master/smrt-server-tools/src/main/resources
might be a quick workaround.

Ideally this should be done programmatically in the code.

**Comment by jfalkner** [comment]
Thanks. I just got there. I had to run `packInstall`. For some reason it seemed that `pack` alone didn't do enough.

**Comment by jfalkner** [comment]
Any pointers for running the above code in debug mode via IntelliJ. I've got the project loaded, but I'm sorting out how to run the equivalent `pack/bin/get-smrt-server-status` via the debugger.

**Comment by jfalkner** [comment]
Never mind. Right-Click and run via Debugger works. Nice.

**Comment by jfalkner** [comment]
The logger notes that we end up with multiple copies of the `logback.xml` config in the class path when `smrt-server-tools` is run. All seem to have similar config.

- [smrt-server-link/src/main/resources/logback.xml](https://github.com/PacificBiosciences/smrtflow/blob/ac5ad0de80fc44806dfc7fd0e5d87aaa9d63c8fe/smrt-server-link/src/main/resources/logback.xml)
- [smrt-server-base/src/main/resources/logback.xml](https://github.com/PacificBiosciences/smrtflow/blob/ac5ad0de80fc44806dfc7fd0e5d87aaa9d63c8fe/smrt-server-base/src/main/resources/logback.xml)
- [smrt-server-analysis/src/main/resources/logback.xml](https://github.com/PacificBiosciences/smrtflow/blob/ac5ad0de80fc44806dfc7fd0e5d87aaa9d63c8fe/smrt-server-analysis/src/main/resources/logback.xml)

A main difference is where the log files are saved. e.g.

```bash
$ diff smrt-server-analysis/src/main/resources/logback.xml smrt-server-link/src/main/resources/logback.xml
38c38
<         <file>${LOG_DIR_PATH:-.}/secondary-smrt-server.log</file>
---
>         <file>${LOG_DIR_PATH:-.}/smrtlink-smrt-server.log</file>
40c40
<             <fileNamePattern>${LOG_DIR_PATH:-.}/secondary-smrt-server.log.%i.gz</fileNamePattern>
---
>             <fileNamePattern>${LOG_DIR_PATH:-.}/smrtlink-smrt-server.log.%i.gz</fileNamePattern>
```

These configs all come from [Akka's `application.conf`](https://github.com/PacificBiosciences/smrtflow/blob/ac5ad0de80fc44806dfc7fd0e5d87aaa9d63c8fe/smrt-analysis/src/main/resources/application.conf) setting `loggers = ["akka.event.slf4j.Slf4jLogger"]`, which means we end up with a [SLF4J logger](http://www.slf4j.org/) that is backed by [Logback](http://logback.qos.ch/index.html) which looks for for `logback.xml` config.

The config has some stuff that looks like it can easily be trimmed. e.g. `<property file="${LOG_PROP_FILE:-./logback.properties}" />` is set but we don't have any `logback.properties` files in our codebase. I may trim these out, but I don't think it helps with the core problem.

I'm still thinking through how to best silence the logging and have sane default + debug modes. I'm inclined to make our own extension of `LazyLogger` that does this and sets reasonable log files based on convention and not config. That'd mean we could delete all of those `logback.xml` files and also have a shared way to toggle on stdout debugging if desired.

**Comment by jfalkner** [comment]
FWIW, our current logger is already configurable at runtime. SLF4 abstracts the standard Java logging, but you still essentially have a `setLevel` method accessible and a way to register or remove handlers.

The bulk of initial logging statements come from SLF4 + Logback. Unfortunately, silencing of them can't be done via the `App` extending class with our current setup.

**Comment by skinner** [comment]
> <property file="${LOG_PROP_FILE:-./logback.properties}" /> is set but we don't have any logback.properties files in our codebase

It's there in perforce:
http://swarm/files/depot/software/smrtanalysis/services-ui/scala/services/smrtlink-smrt-server/logback.properties
http://swarm/files/depot/software/smrtanalysis/services-ui/scala/services/secondary-smrt-server/logback.properties

The logback.properties file is used in the production deployment, so I think we'll want to propagate it to github (or come up with a different way of addressing the same need).  I'm not sure which directory it should go into in the sbt multiproject world, though.

**Comment by skinner** [comment]
Re: multiple logback.xml files, the approach before the sbt multiproject shift was to "merge" them (by discarding some) at `sbt assembly` time:

http://swarm/files/depot/software/smrtanalysis/services-ui/scala/services/secondary-smrt-server/build.sbt?v=199#l72

The idea was that we had this stack of service components (base, smrtlink, secondary), and if you were using one of the lower-level components, you'd have a logback.xml configuration.  But if you were using a stack that included a higher-level component, then you'd get the logback.xml from the higher-level one (by discarding the lower-level ones when you were creating the assembly with the higher-level component).

**Comment by jfalkner** [comment]
Thanks for the context. Makes sense.

**Comment by jfalkner** [comment]
Meetings took a chunk of the day, but I finally had time to look some more at this. It appears that the extra messages we're seeing are actually due to [Logback's default behavior of dumping status when it finds issues with parsing the logback.xml file](http://logback.qos.ch/manual/configuration.html#automaticStatusPrinting).

We have three culprits. Found by looking at the WARN or ERROR messages logged.

- `logback.properties` raises an error because it doesn't exist during dev
- Non-working `<root ...` config. Raises error when doing the conditional logic.
- Multiple copies of `logback.xml` in the the class path.

After fixing all three of these, the logging during startup is then what you'd expect.

```bash
$ ./smrt-server-tools/target/pack/bin/get-smrt-server-status --host smrtlink-bihourly --port 8081 
[DEBUG] [05/11/2016 17:34:21.166] [main] [EventStream] StandardOutLogger started
[DEBUG] [05/11/2016 17:34:21.429] [main] [EventStream(akka://get-status)] logger log1-Slf4jLogger started
[DEBUG] [05/11/2016 17:34:21.429] [main] [EventStream(akka://get-status)] Default Loggers started
URL: http://smrtlink-bihourly:8081
GET http://smrtlink-bihourly:8081: SUCCESS
ServiceStatus(pacbio.smrtservices.smrtlink_analysis,Services have been up for 1 hour, 31 minutes and 11.872 seconds.,5471872,d9bade64-b883-4c5d-9e58-7b172e56489b,0.50.21-SNAPSHOT,secondarytest)
found endpoint /secondary-analysis/job-manager/jobs/import-dataset
...
```

As quick fix to @natechols complaint would be to remove the offending config and tweak the build script so that only one `logback.xml` is on the path.

**Comment by natechols** [comment]
Excellent.  I'm not qualified to judge what the appropriate solution is here but I would upvote anything that simplifies this.

**Comment by skinner** [comment]
I think the right logging configuration for the command line tools is going to be different from the logging configuration for the services.  I think we do want the existing logback config (or something very much like it) for the services, but I agree that it's excessive for the command-line tools.

Can we put a logback.xml into  smrt-server-tools/src/main/resources?  I'm not familiar with the sbt `pack` process, but could we use a mergeStrategy in the smrt-server-tools build.sbt `pack` task to discard the service logback.xml files?  Similar to what we did in the assembly task in the services build.sbt (in the link in my last comment).
