### ISSUE TITLE
Import 3.1.x changes since migration from Perforce

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#23]
Let's do a single bulk sync with the remaining 3.1 changes to make sure the GH repo is synced. 

Then EOL of the code in Perforce.

**Comment by mpkocher** [comment]
@skinner @smcclellan7 @jfalkner @natechols 

During this transition period. We need push back the perforce CLs from 3.1.0 (and potentially if there's a post 3.1.0 patch) to keep this in sync. 

The most recent CL in perforce is 179865

When the 3.1.x is completed, then we can make more aggressive refactorings to leverage the new repo structure. Otherwise, pushing these perforce changes back here could get messy if we start heavily refactoring the code.

**Comment by natechols** [comment]
Are we planning to make 3.1.x use this repo instead of the old p4?  I was assuming the branched p4 repo would join the ranks of the undead while we went crazy in mainline.

**Comment by mpkocher** [comment]
Hopefully the changes fro 3.1.1 will be very limited in scope. Perhaps, only 32730 and 32827.

This would avoid potentially messy merging from p4. Once this is a bit more clear, we can EOL the code in perforce.

**Comment by mpkocher** [comment]
@skinner Do you know if we're all synced with @smcclellan7 and your changes in perforce?

I still need to merge a change to EngineManager.

**Comment by mpkocher** [comment]
I think we're all synced with the 3.1.0 changes.
