### ISSUE TITLE
Port get-status (from bundle/bin) to scala

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#38]
Related to #13

**Comment by mpkocher** [comment]
This will be able to be used will any smrt-server (e.g, paws, transfer, SL/SA, internal analysis)

**Comment by mpkocher** [comment]
@natechols It looks like this is completed?

**Comment by natechols** [comment]
Let me do one more review, otherwise yes.

**Comment by natechols** [comment]
Two things missing:

1. get-status loads the host and port from config.json - the scala version requires these to be specified
2. get-status checks the UI as well

The second one is easy - not sure what to do about the first.

**Comment by mpkocher** [comment]
This has been resolved via `bundler-get-status`.
