### ISSUE TITLE
Implement Idable for Job/Dataset Id/UUID 

### ISSUE THREAD

**Issue by natechols** [PacificBiosciences/smrtflow#40]
The main place this is a problem so far is in the client API and particularly the 'pbservice' replacement - the `PbSmrtPipeServiceOptions` model contains `BoundServiceEntryPoint` where datasetId is `Int`, but we need to be able to handle either Int or UUID in the JSON config files.

**Comment by mpkocher** [comment]
This should use a model similar to this:

https://gist.github.com/mpkocher/8d37114680b9c39d9adb119f74ce76e1

**Comment by mpkocher** [comment]
The IdAble model is in common models subproject. It's adopted in a few places. It will be a continuing effort to clean this up.
