### ISSUE TITLE
daligner_p Segmentation fault   

### ISSUE THREAD

**Issue by wangxinbio** [PacificBiosciences/smrtflow#487]
Hi
I am assemble a genome using HGAP4 in smrtlink-5.1. After several days, I get an error(see bottom). How can I fix it ?
Thanks
Xin 

log file:
{   'eid_subread': '/home01/xinwang/wangxin/denovo/03_HGAP/Subreads.xml'}
Workflow Options:

{   'pbsmrtpipe.options.chunk_mode': True,
    'pbsmrtpipe.options.cluster_manager': None,
    'pbsmrtpipe.options.debug_mode': False,
    'pbsmrtpipe.options.distributed_mode': False,
    'pbsmrtpipe.options.exit_on_failure': False,
    'pbsmrtpipe.options.max_nchunks': 128,
    'pbsmrtpipe.options.max_nproc': 40,
    'pbsmrtpipe.options.max_nworkers': 100,
    'pbsmrtpipe.options.max_total_nproc': 96,
    'pbsmrtpipe.options.progress_status_url': None,
    'pbsmrtpipe.options.tmp_dir': '/tmp'}
Task Options:

{   
.
.
.
.
.
.
Successfully applying chunk operator ['pbsmrtpipe.operators.chunk_task_falcon1_run_daligner_jobs'] to TaskScatterBindingNode ix:pbfalcon.tasks.scatter1_run_daligner_jobs-1 original-task:fa
lcon_ns.tasks.task_falcon1_run_daligner_jobs chunk-group-id:ec83e0e3-f44e-49fc-8a10-a4f36ca1a70b to generate 1 chunked tasks. Chunks:
TaskChunkedBindingNode chunk-id:scattered-daligner-jobs_0 ix:falcon_ns.tasks.task_falcon1_run_daligner_jobs-1 chunk-group-id:ec83e0e3-f44e-49fc-8a10-a4f36ca1a70b
Starting worker falcon_ns.tasks.task_falcon1_run_daligner_jobs-1 (2 workers running, 5 total proc in use)
Task falcon_ns.tasks.task_falcon1_run_daligner_jobs-1 Failed task falcon_ns.tasks.task_falcon1_run_daligner_jobs exit code 1 in 14.16 sec (See file '/home01/xinwang/wangxin/denovo/03_HGAP/tomato_HGP/tasks/falcon_ns.tasks.task_falcon1_run_daligner_jobs-1/stderr'.)
Extracted from stderr
daligner_p -v -k25 -t16 -H500 -e0.93 -mdust preads.1 preads.1
+ daligner_p -v -k25 -t16 -H500 -e0.93 -mdust preads.1 preads.1
/home01/xinwang/wangxin/denovo/03_HGAP/tomato_HGP/tasks/falcon_ns.tasks.task_falcon1_run_daligner_jobs-1/./job_00000000/rj_00000000.sh: line 3: 27951 Segmentation fault      (core dumped) daligner_p -v -k25 -t16 -H500 -e0.93 -mdust preads.1 preads.1
Traceback (most recent call last):

**Comment by pb-devans** [comment]
This repository is probably not the right one to post this to. Best to contact PacBio support directly by email or you could try filing an issue with this repository instead: https://github.com/PacificBiosciences/FALCON
