### ISSUE TITLE
How to import data in SMRT link v6.0.0

### ISSUE THREAD

**Issue by Lcornet** [PacificBiosciences/smrtflow#488]
Hello, i have these data : 
-rw-r----- 1 ulg ulg       40848 Mär 13 05:15 m54073_190312_110456.subreadset.xml
-rw-r----- 1 ulg ulg 34167874206 Mär 13 05:20 m54073_190312_110456.subreads.bam
-rw-r----- 1 ulg ulg    37133375 Mär 13 05:21 m54073_190312_110456.subreads.bam.pbi
-rw-r----- 1 ulg ulg 54259703011 Mär 13 05:29 m54073_190312_110456.scraps.bam
-rw-r----- 1 ulg ulg    51626355 Mär 13 05:29 m54073_190312_110456.scraps.bam.pbi
-rw-r----- 1 ulg ulg          60 Mär 13 05:29 m54073_190312_110456.adapters.fasta
-rw-r----- 1 ulg ulg      105736 Mär 13 05:29 m54073_190312_110456.sts.xml
-rw-r----- 1 ulg ulg      747001 Mär 13 05:29 m54073_190312_110456.baz2bam_1.log
-rw-r----- 1 ulg ulg         535 Mär 13 05:29 m54073_190312_110456.transferdone
-rw-rw---- 1 ulg ulg        3005 Mär 15 11:47 m54073_190312_110456.subreads.json
-rw-rw---- 1 ulg ulg   718853173 Mär 15 12:03 m54073_190312_110456.subreads.stats.csv
-rw-rw---- 1 ulg ulg           0 Mär 15 12:03 m54073_190312_110456.subreads.statsdone

I would like to load into smart link in order to process with CCS barcod pipeline. 
I don't found how to import in Data Management, the only option are fast or xml.
Can you help, please ?

Thanks,

**Comment by natechols** [comment]
The subreadset.xml is the file you need to import.

PS. This is not the appropriate place to ask for SMRT Link help; please contact PacBio tech support in the future.
