### ISSUE TITLE
Verbose Slick logging 

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#49]
When running the tests, or when running `sbt smrt-server-analysis/assembly`, then `java -jar` I am seeing  a lot of slick logging. 

The logging is currently far too verbose, we would need to address this before deploying.

**Comment by jfalkner** [comment]
Thanks @mpkocher. Noted also in #50 and will have fix up shortly. Seems some `dependsOn` were needed for SBT to include the JAR and enable the new default logger config.
