### ISSUE TITLE
Add Readme.md to each subproject

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#54]
Add a terse high-level overview of each sbt subproject

**Comment by mpkocher** [comment]
We'll rotate this using https://github.com/PacificBiosciences/smrtflow/blob/master/smrt-server-logging/Readme.md as an example

It should be minimal. This overlaps with the 'real' documentation that is done in rst.

**Comment by jfalkner** [comment]
SGTM. The Readme.md should include a link to the rst docs too -- I guess it'll mostly point to http://smrtflow.readthedocs.io/en/latest/ ?

Do we have notes anywhere on making the rst docs?

**Comment by mpkocher** [comment]
It's using sphinx. 

http://www.sphinx-doc.org/en/stable/

pip install -r REQUIREMENTS.txt should install the necessary requirements for the docs.

**Comment by mpkocher** [comment]
@jfalkner  Can you add a terse readme to each sub-project defining what it does at a high level?

**Comment by jfalkner** [comment]
Yes, will do. I'll ask as I need help when sorting out examples. e.g. I'm unsure what a good example use of `smrt-server-analysis-internal` would be.

**Comment by mpkocher** [comment]
The internal case has a readme.

https://github.com/PacificBiosciences/smrtflow/blob/master/smrt-server-analysis-internal/Readme.md

**Comment by jfalkner** [comment]
Nice, thanks for the pointer. I missed that.
