### ISSUE TITLE
enable smrt-server-logging configuration in the server

### ISSUE THREAD

**Issue by skinner** [PacificBiosciences/smrtflow#55]
We used to supply a properties file at server startup time, and the logback.xml files would reference those properties.  Now that the logback.xml files are gone, we don't have a way for the services to take logging configuration like the file to log to.

Jayson has added command-line parameter processing for the command-line tools.  But for the server programs, I'm not sure if the command line is the nice way to do it.  Maybe com.pacbio.logging.LoggerConfigurator could look at system properties and use them?  Or maybe it could load our existing properties file if we pass that as a system property?

**Comment by jfalkner** [comment]
> com.pacbio.logging.LoggerConfigurator could look at system properties and use them? Or maybe it could load our existing properties file if we pass that as a system property?

Yes, both would be straight-forward to do. I'll add a property option lookup as a -D arg.

Alternatively, logback.xml in the classpath should still trump the Configurator. According to the docs: http://logback.qos.ch/manual/configuration.html#auto_configuration

Should test it though

**Comment by jfalkner** [comment]
Originally, I did assume we could add the new logging args to the server code. It'd be helpful to review why that may not work.

**Comment by skinner** [comment]
> Originally, I did assume we could add the new logging args to the server code. It'd be helpful to review why that may not work.

I think the server probably could take command line args; I've just never looked into exactly how that works.  The server doesn't have the command-line machinery that the command-line tools have.  The server initialization mostly happens in:

smrt-server-analysis/src/main/scala/com/pacbio/secondary/smrtserver/appcomponents/SecondaryAnalysisApp.scala
smrt-server-base/src/main/scala/com/pacbio/common/app/BaseSmrtServerApp.scala
smrt-server-link/src/main/scala/com/pacbio/secondary/smrtlink/app/SmrtLinkApp.scala

If you see a nice way to process command-line args there and pass them to LoggerConfig, that's fine with me.  It would mean that we'd have to change the [script that launches the server](http://swarm/files/depot/software/smrtanalysis/services-ui/pbservice-bundler/smrtlink_services_ui/bin/start?v=17#l113-118); it's not a huge change, but we'd want to coordinate that change with the changeover to using github as the source for the server code.

> Alternatively, logback.xml in the classpath should still trump the Configurator

Since you replicated what the logback.xml files were doing (with file rotation, etc.) in com.pacbio.logging.LoggerConfig, it seems natural for the server to use LoggerConfig and just pass a few config params.  I don't see any reason to resurrect the logback.xml files and hand one to the server if their functionality exists in LoggerConfig.

The server just doesn't currently have a way to receive those config params and pass them to LoggerConfig.  Individual command-line params or properties doesn't make a big difference to me; I thought having LoggerConfigurator load a property file might be the simpler change (because changing the *App files to acquire command line params seemed like it might be more complex), but if not, that's cool.

**Comment by jfalkner** [comment]
Thanks for the links. Makes sense. I'll take a deeper look at the code and take a stab at what seems to work best.

**Comment by skinner** [comment]
For testing, you can launch a server by (from the smrtflow dir):
```
sbt smrt-server-analysis/assembly
cd smrt-server-analysis
mkdir db
java -jar target/scala-2.11/smrt-server-analysis*.jar
```

I've been developing using `sbt run` a lot of the time, but it looks like the git transition left some rough edges there.

**Comment by mpkocher** [comment]
We should try to delete those references to db/*

**Comment by jfalkner** [comment]
> For testing, you can launch a server by (from the smrtflow dir):

Thanks. Saved me from asking how to run! It looks like right-click and run or debug from IntelliJ works and runs the same too, albeit same `db` issue.

> We should try to delete those references to db/*

I just split this out to #58. If it seems like quick cleanup, I'll take a stab at cleaning it up.
