### ISSUE TITLE
Add scalastyle XML

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#62]
- Add doc on how to wire it to Intellij
- Then a single commit to fix everything using this style format

**Comment by mpkocher** [comment]
I would prefer to use the twitter config or some other project versus writing our own from scratch.

**Comment by jfalkner** [comment]
[Scalafmt](https://olafurpg.github.io/scalafmt/) seems like a decent fit. The mindset behind the work matches most of why I think it is helpful to have these tools. Also has simple SBT, CLI and IntelliJ support.

I'm reading the docs and watching the videos. If it still seems good, I'll try it out on our code.

**Comment by jfalkner** [comment]
Near the end of the [scalafmt talk](https://vimeo.com/165929294), the author notes some features that'd be nice. One is lack of a `scala-tidy` tool that can rearrange imports. It ends up being non-trival and needs some attention.

**Comment by jfalkner** [comment]
Oops, should have noted here is [Scalastyle.org](http://www.scalastyle.org/). May be worth starting with that.

**Comment by jfalkner** [comment]
Leaving some Scalastyle.org notes here. I've tried to look up what other orgs are using, [namely twitter's Effective Scala](http://twitter.github.io/effectivescala/#Formatting). I've yet to find a good resource for a style checker config we can simply reuse. For the most part, it appears that people try to follow the [Scala style guide](http://docs.scala-lang.org/style/) plus clarify some cases that aren't easily auto-checked.

I'll propose we attempt to abide by what is noted in Effective Scala but only enforce the subset of stuff (mostly what is practical to check). Hopefully not too onerous.
