### ISSUE TITLE
Add git sha to Version string exposed in /status

### ISSUE THREAD

**Issue by mpkocher** [PacificBiosciences/smrtflow#84]
properties.version has the git sha, we should append the version string in /status with this value

**Comment by jfalkner** [comment]
I'll assumed this is `/status` when running smrt-server-analysis. If not the case, please note in thread.

Here is what I'm seeing currently. It does look as if the SHA is missing with `"version": "unknown version"`.

```bash
# run the server
sbt smrt-server-analysis/run &

# GET /status URI
$ curl http://localhost:8070/status
{
  "uuid": "25db9e0c-4744-41fa-8bde-db0030c7a191",
  "version": "unknown version",
  "id": "pacbio.smrtservices.smrtlink_analysis",
  "uptime": 592513,
  "message": "Services have been up for 9 minutes and 52.513 seconds.",
  "user": "jfalkner"
}
```

**Comment by jfalkner** [comment]
Looks like this file ends up in the root dir of the `smrt-common-models` classpath. @mpkocher please correct me if this isn't this right file. The name `s/properties.version/version.properties`.

```bash
$ find . -name '*version*'
./smrt-common-models/target/scala-2.11/classes/version.properties
```

**Comment by mpkocher** [comment]
Run from a jar file and the version will show up as X.Y.Z-SNAPSHOT. Running from within sbt will yield the "unknown version" case.

"version.properties" is the correct file. See build.sbt for details.

My suggestion is to drop the SNAPSHOT and append with the first 7 values of the SHA (similar to how github works).

**Comment by jfalkner** [comment]
Reopening. Clarified that the expected version is of the format `0.1.2-af4a30e` not `af4a30e670a76f3a38e2fdc420455c830e0dc479` as shown below.

```
{
 "uuid": "f18647c4-591a-462c-8867-96fc28c26505",
 "version": "af4a30e670a76f3a38e2fdc420455c830e0dc479",
 "id": "pacbio.smrtservices.smrtlink_analysis",
 "uptime": 4388,
 "message": "Services have been up for 4.388 seconds.",
 "user": "jfalkner"
}
```
